// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Kegiatan struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Status string `json:"status"`
	User   *User  `json:"user"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewKegiatan struct {
	Title  string `json:"title"`
	Status string `json:"status"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
